[2021-12-14 17:49:47,314] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2021-12-13T00:00:00+00:00 [queued]>
[2021-12-14 17:49:47,325] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2021-12-13T00:00:00+00:00 [queued]>
[2021-12-14 17:49:47,325] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 17:49:47,325] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-14 17:49:47,325] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 17:49:47,346] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): processing_user> on 2021-12-13T00:00:00+00:00
[2021-12-14 17:49:47,347] {standard_task_runner.py:52} INFO - Started process 22611 to run task
[2021-12-14 17:49:47,354] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_user', '2021-12-13T00:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_precessing.py', '--cfg-path', '/tmp/tmpe5rqtrf9', '--error-file', '/tmp/tmphb5oeiey']
[2021-12-14 17:49:47,355] {standard_task_runner.py:77} INFO - Job 7: Subtask processing_user
[2021-12-14 17:49:47,420] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.processing_user 2021-12-13T00:00:00+00:00 [running]> on host airflowvm
[2021-12-14 17:49:47,517] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-13T00:00:00+00:00
[2021-12-14 17:49:47,525] {python.py:151} INFO - Done. Returned value was: None
[2021-12-14 17:49:47,528] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211213T000000, start_date=20211214T174947, end_date=20211214T174947
[2021-12-14 17:49:47,550] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-14 17:49:47,589] {local_task_job.py:151} INFO - Task exited with return code 0
