[2021-12-29 14:27:03,852] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task2 2021-12-28T00:00:00+00:00 [queued]>
[2021-12-29 14:27:03,888] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task2 2021-12-28T00:00:00+00:00 [queued]>
[2021-12-29 14:27:03,888] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 14:27:03,888] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-29 14:27:03,888] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 14:27:03,900] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task2> on 2021-12-28T00:00:00+00:00
[2021-12-29 14:27:03,916] {standard_task_runner.py:52} INFO - Started process 11227 to run task
[2021-12-29 14:27:03,930] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task2', '2021-12-28T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmpwsvbwgkr', '--error-file', '/tmp/tmp2ijjex9o']
[2021-12-29 14:27:03,933] {standard_task_runner.py:77} INFO - Job 44: Subtask task2
[2021-12-29 14:27:04,223] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task2 2021-12-28T00:00:00+00:00 [running]> on host airflowvm
[2021-12-29 14:27:04,503] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T00:00:00+00:00
[2021-12-29 14:27:04,504] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-29 14:27:04,504] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 0']
[2021-12-29 14:27:04,521] {subprocess.py:75} INFO - Output:
[2021-12-29 14:27:04,529] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-29 14:27:04,570] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=trigger_rule, task_id=task2, execution_date=20211228T000000, start_date=20211229T142703, end_date=20211229T142704
[2021-12-29 14:27:04,672] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-29 14:27:04,700] {local_task_job.py:151} INFO - Task exited with return code 0
